version: '3'

networks:
  showdocnet:

services:
  showdoc:
    ## 方式1: 官方 image ################################
    # image: star7th/showdoc

    ## 方式2: 源码 build image ################################
    ## 国内构建镜像方式1: docker compose build --build-arg IN_CHINA=true
    ## 国内构建镜像方式2: IN_CHINA=true docker compose build
    ## 启动: IN_CHINA=true docker compose up -d
    build:
      context: ./
      args:
        - IN_CHINA=${IN_CHINA:-false}
    environment:
      IN_CHINA: ${IN_CHINA:-false}
    hostname: showdoc
    ports:
      - 4999:80
    volumes:
      ## 兼容历史版本文件
      - /showdoc_data:/showdoc_data_old
      - ./showdocdata/html:/var/www/html
    restart: always
    tty: true
    networks:
      - showdocnet